In [1]:
import pandas as pd 
import openpyxl

In [3]:
df_dicc = pd.read_excel("./Diccionario_Variables_Alumnos.xlsx")
df_dicc_copia1 = df_dicc.copy()

In [4]:
df_dicc_copia1.head(5)

,Variables,Descripción,Valores
0,ID,Identificador único del préstamo.,Código identificador del cliente.
1,Edad,Edad del prestatario.,Valor numérico.
2,Ingresos,Ingreso anual del prestatario.,Valor numérico.
3,Monto_Inicial,Cantidad de dinero acordada.,Valor numérico.
4,Scoring_Crediticio,"La puntuación crediticia del prestatario, que ...",Valor numérico.

In [6]:
df_prestamos = pd.read_excel("./Prestamos_Data_Alumnos_v5.xlsx")
df_prestamos_copia1 = df_prestamos.copy()

In [12]:
df_prestamos_copia1.head(5)

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
0,O77MPJ,26,19153.0,6973,706,9.0,1,19.05,36.0,0.10,Grado Universitario,Jornada completa,Soltero,0.0,1.0,Automóvil,1.0,1,130.83
8,IYOL1S,29,39531.0,40000,826,0.0,1,9.74,24.0,0.19,Doctorado,Jornada completa,Casado,0.0,0.0,Automóvil,1.0,0,208.64
9,FRMZVN,29,40348.0,16448,740,9.0,1,14.73,24.0,0.10,Máster,Jornada completa,Soltero,0.0,1.0,Automóvil,0.0,1,101.94
26,YKHXVY,38,41732.0,42040,661,173.0,2,13.24,48.0,0.18,Grado Universitario,Tiempo parcial,Casado,1.0,0.0,Automóvil,1.0,1,800.00
32,NHDJTK,35,35085.0,16406,759,181.0,1,9.74,36.0,0.13,Escolar,Jornada completa,Casado,0.0,1.0,Automóvil,0.0,0,94.42

In [8]:
df_prestamos_copia1=df_prestamos_copia1[df_prestamos_copia1["Proposito"] == "Automóvil"]

In [9]:
df_prestamos_copia1.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
0,O77MPJ,26,19153.0,6973,706,9.0,1,19.05,36.0,0.10,Grado Universitario,Jornada completa,Soltero,0.0,1.0,Automóvil,1.0,1,130.83
8,IYOL1S,29,39531.0,40000,826,0.0,1,9.74,24.0,0.19,Doctorado,Jornada completa,Casado,0.0,0.0,Automóvil,1.0,0,208.64
9,FRMZVN,29,40348.0,16448,740,9.0,1,14.73,24.0,0.10,Máster,Jornada completa,Soltero,0.0,1.0,Automóvil,0.0,1,101.94
26,YKHXVY,38,41732.0,42040,661,173.0,2,13.24,48.0,0.18,Grado Universitario,Tiempo parcial,Casado,1.0,0.0,Automóvil,1.0,1,800.00
32,NHDJTK,35,35085.0,16406,759,181.0,1,9.74,36.0,0.13,Escolar,Jornada completa,Casado,0.0,1.0,Automóvil,0.0,0,94.42

In [10]:
df_prestamos_copia1.info

<bound method DataFrame.info of             ID  Edad  Ingresos  Monto_Inicial  Scoring_Crediticio  \
0       O77MPJ    26   19153.0           6973                 706
8       IYOL1S    29   39531.0          40000                 826
9       FRMZVN    29   40348.0          16448                 740
26      YKHXVY    38   41732.0          42040                 661
32      NHDJTK    35   35085.0          16406                 759
...        ...   ...       ...            ...                 ...
510685  9DP3XV    36   45006.0          40252                 746
510686  R30LLT    42   44124.0          15509                 574
510687  W2Y3KE    44   84570.0         331820                 791
510695  WVJ9ZC    42   61642.0          19371                 502
510700  6903JQ    42   33486.0          33048                 760

        Meses_Empleo  Num_Creditos  Ratio_Interes  Duracion  \
0                9.0             1          19.05      36.0
8                0.0             1           9.74      24.0
9                9.0             1          14.73      24.0
26             173.0             2          13.24      48.0
32             181.0             1           9.74      36.0
...              ...           ...            ...       ...
510685         144.0             1          12.74      36.0
510686         246.0             2           8.00      24.0
510687         246.0             2           6.90      60.0
510695         223.0             3           8.55      12.0
510700         206.0             1           9.09      24.0

        Ratio_Deuda_Ingresos             Estudios Tipo_Jornada_Laboral  \
0                       0.10  Grado Universitario     Jornada completa
8                       0.19            Doctorado     Jornada completa
9                       0.10               Máster     Jornada completa
26                      0.18  Grado Universitario       Tiempo parcial
32                      0.13              Escolar     Jornada completa
...                      ...                  ...                  ...
510685                  0.55  Grado Universitario     Jornada completa
510686                  0.17  Grado Universitario             Autónomo
510687                  0.55            Doctorado       Tiempo parcial
510695                  0.10               Máster       Tiempo parcial
510700                  0.31  Grado Universitario             Autónomo

       Estado_Civil  Posesion_Hipoteca  Personas_Cargo  Proposito  Fiador  \
0           Soltero                0.0             1.0  Automóvil     1.0
8            Casado                0.0             0.0  Automóvil     1.0
9           Soltero                0.0             1.0  Automóvil     0.0
26           Casado                1.0             0.0  Automóvil     1.0
32           Casado                0.0             1.0  Automóvil     0.0
...             ...                ...             ...        ...     ...
510685       Casado                0.0             0.0  Automóvil     1.0
510686      Soltero                0.0             1.0  Automóvil     0.0
510687       Casado                1.0             0.0  Automóvil     0.0
510695       Casado                1.0             1.0  Automóvil     0.0
510700   Divorciado                0.0             0.0  Automóvil     0.0

        Impago   Prima
0            1  130.83
8            0  208.64
9            1  101.94
26           1  800.00
32           0   94.42
...        ...     ...
510685       0  563.25
510686       0   92.40
510687       0  800.00
510695       0  128.22
510700       0  172.41

[76930 rows x 19 columns]>